### ISSUE TITLE
warlock RB dimensional bullet instant cast

### ISSUE THREAD

**Issue by covertrui** [dakaringer/BnS-ST#3]
sorry for more issues opened! the 4-2 path on RB on your skill tree also displays instant cast on down, (other cc) etc but in the CN ver it seems only rank 1 does that? I don't know if that's an inconsistency across versions or if that's an error...
![_150122_000](https://cloud.githubusercontent.com/assets/10627201/5852808/564ce352-a1d1-11e4-99a7-48ae918b3a61.jpg)

**Comment by dakaringer** [comment]
Yeah... it's a translation bug. It should be instant cast on seized, force
gripped foes
